# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hetu/checkpointing/v1/events.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hetu.cosmos.hetu.checkpointing.v1 import checkpoint_pb2 as hetu_dot_checkpointing_dot_v1_dot_checkpoint__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"hetu/checkpointing/v1/events.proto\x12\x15hetu.checkpointing.v1\x1a&hetu/checkpointing/v1/checkpoint.proto\"k\n\x1b\x45ventCheckpointAccumulating\x12L\n\ncheckpoint\x18\x01 \x01(\x0b\x32,.hetu.checkpointing.v1.RawCheckpointWithMetaR\ncheckpoint\"e\n\x15\x45ventCheckpointSealed\x12L\n\ncheckpoint\x18\x01 \x01(\x0b\x32,.hetu.checkpointing.v1.RawCheckpointWithMetaR\ncheckpoint\"h\n\x18\x45ventCheckpointSubmitted\x12L\n\ncheckpoint\x18\x01 \x01(\x0b\x32,.hetu.checkpointing.v1.RawCheckpointWithMetaR\ncheckpoint\"h\n\x18\x45ventCheckpointConfirmed\x12L\n\ncheckpoint\x18\x01 \x01(\x0b\x32,.hetu.checkpointing.v1.RawCheckpointWithMetaR\ncheckpoint\"h\n\x18\x45ventCheckpointFinalized\x12L\n\ncheckpoint\x18\x01 \x01(\x0b\x32,.hetu.checkpointing.v1.RawCheckpointWithMetaR\ncheckpoint\"h\n\x18\x45ventCheckpointForgotten\x12L\n\ncheckpoint\x18\x01 \x01(\x0b\x32,.hetu.checkpointing.v1.RawCheckpointWithMetaR\ncheckpoint\"\xd2\x01\n\x1a\x45ventConflictingCheckpoint\x12[\n\x16\x63onflicting_checkpoint\x18\x01 \x01(\x0b\x32$.hetu.checkpointing.v1.RawCheckpointR\x15\x63onflictingCheckpoint\x12W\n\x10local_checkpoint\x18\x02 \x01(\x0b\x32,.hetu.checkpointing.v1.RawCheckpointWithMetaR\x0flocalCheckpointB7Z5github.com/hetu-project/hetu/v1/x/checkpointing/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hetu.checkpointing.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/hetu-project/hetu/v1/x/checkpointing/types'
  _globals['_EVENTCHECKPOINTACCUMULATING']._serialized_start=101
  _globals['_EVENTCHECKPOINTACCUMULATING']._serialized_end=208
  _globals['_EVENTCHECKPOINTSEALED']._serialized_start=210
  _globals['_EVENTCHECKPOINTSEALED']._serialized_end=311
  _globals['_EVENTCHECKPOINTSUBMITTED']._serialized_start=313
  _globals['_EVENTCHECKPOINTSUBMITTED']._serialized_end=417
  _globals['_EVENTCHECKPOINTCONFIRMED']._serialized_start=419
  _globals['_EVENTCHECKPOINTCONFIRMED']._serialized_end=523
  _globals['_EVENTCHECKPOINTFINALIZED']._serialized_start=525
  _globals['_EVENTCHECKPOINTFINALIZED']._serialized_end=629
  _globals['_EVENTCHECKPOINTFORGOTTEN']._serialized_start=631
  _globals['_EVENTCHECKPOINTFORGOTTEN']._serialized_end=735
  _globals['_EVENTCONFLICTINGCHECKPOINT']._serialized_start=738
  _globals['_EVENTCONFLICTINGCHECKPOINT']._serialized_end=948
# @@protoc_insertion_point(module_scope)
