# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hetu/checkpointing/v1/tx.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hetu.cosmos.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from hetu.cosmos.cosmos.staking.v1beta1 import tx_pb2 as cosmos_dot_staking_dot_v1beta1_dot_tx__pb2
from hetu.cosmos.cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ehetu/checkpointing/v1/tx.proto\x12\x15hetu.checkpointing.v1\x1a\x14gogoproto/gogo.proto\x1a\x1f\x63osmos/staking/v1beta1/tx.proto\x1a\x17\x63osmos/msg/v1/msg.proto\"\xcc\x01\n\x12MsgRegistValidator\x12\\\n\nbls_pubkey\x18\x01 \x01(\x0c\x42=\xda\xde\x1f\x39github.com/hetu-project/hetu/v1/crypto/bls12381.PublicKeyR\tblsPubkey\x12+\n\x11validator_address\x18\x02 \x01(\tR\x10validatorAddress\x12\x16\n\x06sender\x18\x03 \x01(\tR\x06sender:\x13\x88\xa0\x1f\x00\xe8\xa0\x1f\x00\x82\xe7\xb0*\x06sender\"\x1c\n\x1aMsgRegistValidatorResponse\"p\n\x16MsgRegistStakeContract\x12)\n\x10\x63ontract_address\x18\x01 \x01(\tR\x0f\x63ontractAddress\x12\x16\n\x06sender\x18\x02 \x01(\tR\x06sender:\x13\x88\xa0\x1f\x00\xe8\xa0\x1f\x00\x82\xe7\xb0*\x06sender\" \n\x1eMsgRegistStakeContractResponse\"\xe9\x01\n\x0eMsgBLSCallback\x12\x1b\n\tepoch_num\x18\x01 \x01(\x04R\x08\x65pochNum\x12P\n\taddr_sigs\x18\x02 \x03(\x0b\x32\x33.hetu.checkpointing.v1.MsgBLSCallback.AddrSigsEntryR\x08\x61\x64\x64rSigs\x12\x16\n\x06sender\x18\x03 \x01(\tR\x06sender\x1a;\n\rAddrSigsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01:\x13\x88\xa0\x1f\x00\xe8\xa0\x1f\x00\x82\xe7\xb0*\x06sender\"\x18\n\x16MsgBLSCallbackResponse2\xdf\x02\n\x03Msg\x12o\n\x0fRegistValidator\x12).hetu.checkpointing.v1.MsgRegistValidator\x1a\x31.hetu.checkpointing.v1.MsgRegistValidatorResponse\x12{\n\x13RegistStakeContract\x12-.hetu.checkpointing.v1.MsgRegistStakeContract\x1a\x35.hetu.checkpointing.v1.MsgRegistStakeContractResponse\x12\x63\n\x0b\x42LSCallback\x12%.hetu.checkpointing.v1.MsgBLSCallback\x1a-.hetu.checkpointing.v1.MsgBLSCallbackResponse\x1a\x05\x80\xe7\xb0*\x01\x42\x37Z5github.com/hetu-project/hetu/v1/x/checkpointing/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hetu.checkpointing.v1.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/hetu-project/hetu/v1/x/checkpointing/types'
  _globals['_MSGREGISTVALIDATOR'].fields_by_name['bls_pubkey']._loaded_options = None
  _globals['_MSGREGISTVALIDATOR'].fields_by_name['bls_pubkey']._serialized_options = b'\332\336\0379github.com/hetu-project/hetu/v1/crypto/bls12381.PublicKey'
  _globals['_MSGREGISTVALIDATOR']._loaded_options = None
  _globals['_MSGREGISTVALIDATOR']._serialized_options = b'\210\240\037\000\350\240\037\000\202\347\260*\006sender'
  _globals['_MSGREGISTSTAKECONTRACT']._loaded_options = None
  _globals['_MSGREGISTSTAKECONTRACT']._serialized_options = b'\210\240\037\000\350\240\037\000\202\347\260*\006sender'
  _globals['_MSGBLSCALLBACK_ADDRSIGSENTRY']._loaded_options = None
  _globals['_MSGBLSCALLBACK_ADDRSIGSENTRY']._serialized_options = b'8\001'
  _globals['_MSGBLSCALLBACK']._loaded_options = None
  _globals['_MSGBLSCALLBACK']._serialized_options = b'\210\240\037\000\350\240\037\000\202\347\260*\006sender'
  _globals['_MSG']._loaded_options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSGREGISTVALIDATOR']._serialized_start=138
  _globals['_MSGREGISTVALIDATOR']._serialized_end=342
  _globals['_MSGREGISTVALIDATORRESPONSE']._serialized_start=344
  _globals['_MSGREGISTVALIDATORRESPONSE']._serialized_end=372
  _globals['_MSGREGISTSTAKECONTRACT']._serialized_start=374
  _globals['_MSGREGISTSTAKECONTRACT']._serialized_end=486
  _globals['_MSGREGISTSTAKECONTRACTRESPONSE']._serialized_start=488
  _globals['_MSGREGISTSTAKECONTRACTRESPONSE']._serialized_end=520
  _globals['_MSGBLSCALLBACK']._serialized_start=523
  _globals['_MSGBLSCALLBACK']._serialized_end=756
  _globals['_MSGBLSCALLBACK_ADDRSIGSENTRY']._serialized_start=676
  _globals['_MSGBLSCALLBACK_ADDRSIGSENTRY']._serialized_end=735
  _globals['_MSGBLSCALLBACKRESPONSE']._serialized_start=758
  _globals['_MSGBLSCALLBACKRESPONSE']._serialized_end=782
  _globals['_MSG']._serialized_start=785
  _globals['_MSG']._serialized_end=1136
# @@protoc_insertion_point(module_scope)
