# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hetu.cosmos.hetu.checkpointing.v1 import tx_pb2 as hetu_dot_checkpointing_dot_v1_dot_tx__pb2


class MsgStub(object):
    """Msg defines the checkpointing Msg service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistValidator = channel.unary_unary(
                '/hetu.checkpointing.v1.Msg/RegistValidator',
                request_serializer=hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgRegistValidator.SerializeToString,
                response_deserializer=hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgRegistValidatorResponse.FromString,
                _registered_method=True)
        self.RegistStakeContract = channel.unary_unary(
                '/hetu.checkpointing.v1.Msg/RegistStakeContract',
                request_serializer=hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgRegistStakeContract.SerializeToString,
                response_deserializer=hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgRegistStakeContractResponse.FromString,
                _registered_method=True)
        self.BLSCallback = channel.unary_unary(
                '/hetu.checkpointing.v1.Msg/BLSCallback',
                request_serializer=hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgBLSCallback.SerializeToString,
                response_deserializer=hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgBLSCallbackResponse.FromString,
                _registered_method=True)


class MsgServicer(object):
    """Msg defines the checkpointing Msg service.
    """

    def RegistValidator(self, request, context):
        """RegistValidator defines a method for registering a new validator of the checkpoint network
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistStakeContract(self, request, context):
        """RegistStakeContract defines a method for registering a validator's staking contract address
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BLSCallback(self, request, context):
        """BLSCallback defines a method for uploading BLS signature
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistValidator': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistValidator,
                    request_deserializer=hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgRegistValidator.FromString,
                    response_serializer=hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgRegistValidatorResponse.SerializeToString,
            ),
            'RegistStakeContract': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistStakeContract,
                    request_deserializer=hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgRegistStakeContract.FromString,
                    response_serializer=hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgRegistStakeContractResponse.SerializeToString,
            ),
            'BLSCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.BLSCallback,
                    request_deserializer=hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgBLSCallback.FromString,
                    response_serializer=hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgBLSCallbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hetu.checkpointing.v1.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hetu.checkpointing.v1.Msg', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Msg defines the checkpointing Msg service.
    """

    @staticmethod
    def RegistValidator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hetu.checkpointing.v1.Msg/RegistValidator',
            hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgRegistValidator.SerializeToString,
            hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgRegistValidatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistStakeContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hetu.checkpointing.v1.Msg/RegistStakeContract',
            hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgRegistStakeContract.SerializeToString,
            hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgRegistStakeContractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BLSCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hetu.checkpointing.v1.Msg/BLSCallback',
            hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgBLSCallback.SerializeToString,
            hetu_dot_checkpointing_dot_v1_dot_tx__pb2.MsgBLSCallbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
